
services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - 3_tier
    depends_on:
      - db
      - backend

  backend:
    image: bitnami/wordpress
    environment:
      - WORDPRESS_USERNAME=user
      - WORDPRESS_PASSWORD=bitnami
      - WORDPRESS_DATABASE=bitnami_wordpress
      - WORDPRESS_DATABASE_HOST=db
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_ENABLE_REVERSE_PROXY=yes
      - WORDPRESS_DATA_TO_PERSIST=wp-config.php wp-content
    volumes:
      - wordpress_data:/bitnami/wordpress
    networks:
      - 3_tier
    depends_on:
      - db

  db:
    image: bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_ROOT_USER=root
    volumes:
      - .host/mariadb_data:/var/lib/mysql
    networks:
      - 3_tier

networks:
  3_tier:
volumes:
  mariadb_data:
  wordpress_data:

